### ISSUE TITLE
[Client Crash] Moving some vanilla assets cause a crash when loading the save

### ISSUE THREAD

**Issue by Dumpy250** [Powback/MapEditor#374]
Moving vanilla assets in the editor and saving will semi-corrupt the save when it is being reloaded later
The fix would be to open the save text file and editing out certain lines of code that were created as a result of moving the vanilla assets
they are referred to as WorldPartData

**Comment by paulhobbel** [comment]
[BrokenOman July 18th.txt](https://github.com/BF3RM/MapEditor/files/9272628/BrokenOman.July.18th.txt)
[Fixed_Oman_july_18.txt](https://github.com/BF3RM/MapEditor/files/9272642/Fixed_Oman_july_18.txt)

**Comment by FoolHen** [comment]
These seem to be causing the issue, rest are fine. Will investigate.

Objects/Vegetation/TreePalm_L_01/TreePalm_L_01
Objects/Vegetation/TreeParkTrees/ParkTree_02

Crash ID: dd54921e-c518-4625-aee6-253f986ea8b5
Build Number: 19006
Release Branch: prod

Edit: Note for me, i suspect this is related to vegetation patching

**Comment by FoolHen** [comment]
Crash happens after loading, when flying over. As a workaround for now, increase the SAVE_LOAD_DELAY value in ext/shared/config.lua. The issue seems to occur when you modify some objects in the client some time after the server, not sure how this can be fixed yet. Increasing the delay makes it so the vanilla objects are modified at the same time in server and client, tho it will crash if someone joins after the save has been loaded or you reconnect.

**Comment by FoolHen** [comment]
Note: might be fixable by modifying the blueprint, maybe the cause its the isnetworked flag or something related.

**Comment by FlashHit** [comment]
Checked an azadi savefile and it seems to crash when it tries to access the mesh of a staticmodelentity. Not sure what’s going on there and if it’s the same issue.

**Comment by FoolHen** [comment]
This was fixed, not sure when
